name: iOS
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        node: [10, 12, 14]
        arch: [x86]
        exclude:
          - { os: macos-latest, arch: x86 }
    # runs-on: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: yarn install
      - run: npm run build
      - run: xcode-select -p
      - run: pod install
        working-directory: example/base/ios
        name: Install pod dependencies

      - name: Build iOS (debug)
        working-directory: example/base
        run: |
          pwd
          xcodebuild \
            -workspace $PWD/ios/examples.xcworkspace \
            -scheme examples \
            clean archive \
            -sdk iphoneos \
            -configuration Debug \
            -UseModernBuildSystem=NO \
            -archivePath $PWD/examples \
            CODE_SIGNING_ALLOWED=NO